---
- name: Restart SSH
  ansible.builtin.service:
    name: "{{ ssh_service }}"
    state: restarted
    enabled: true

- name: Source file
  ansible.builtin.command:
    cmd: "source {{ file_to_source }}"
    creates: "{{ file_to_source }}"
  when: file_to_source is defined
