---
- name: "All servers"
  hosts: all
  become: true
  vars_files:
    - vars/main.yaml
    - vault.txt
  tasks:
    - name: "Common OS tasks"
      ansible.builtin.include_role:
        name: os_common

    - name: "Firewall tasks"
      ansible.builtin.include_role:
        name: firewall

    - name: "Docker install"
      ansible.builtin.include_role:
        name: docker_install

    - name: "K3s install"
      ansible.builtin.include_role:
        name: k3s_install

    - name: "Cert manager install and config"
      ansible.builtin.include_role:
        name: cert_manager

    - name: "Sealed Secrets install"
      ansible.builtin.include_role:
        name: sealed_secrets

    - name: "Rancher dashboard"
      ansible.builtin.include_role:
        name: rancher

    - name: "MinIO object storage"
      ansible.builtin.include_role:
        name: minio

    - name: "Prometheus metrics"
      ansible.builtin.include_role:
        name: prometheus

    - name: "Grafana dashboards"
      ansible.builtin.include_role:
        name: grafana

    - name: "Loki logs"
      ansible.builtin.include_role:
        name: loki
